## Array

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
print(type(arr))
print(arr.shape)
print(arr[0],arr[1],arr[2])
arr[0] = 5
arr

<class 'numpy.ndarray'>
(3,)
1 2 3


array([5, 2, 3])

In [3]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2.shape)
arr2

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
print(arr2[0][0])
print(arr2[0,1])

1
2


#### Create useful array

In [5]:
a = np.zeros((2,2)) # Create an array of all zeros
a

array([[0., 0.],
       [0., 0.]])

In [6]:
b = np.ones((2,2))
b

array([[1., 1.],
       [1., 1.]])

In [7]:
c = np.full((2,2),7)
c

array([[7, 7],
       [7, 7]])

In [8]:
d = np.eye(2)
d

array([[1., 0.],
       [0., 1.]])

In [9]:
e = np.random.random((2,2))
e

array([[0.57365705, 0.91806744],
       [0.06659597, 0.01735118]])

## Array Indexing

In [10]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
b = a[:2,1:3]
b

array([[2, 3],
       [6, 7]])

In [12]:
print(b[0][0])
b[0][0] = 100

2


In [13]:
print(a)

[[  1 100   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [14]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a, a.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4)


In [15]:
row1 = a[1, :]
print(row1, row1.shape)
row2 = a[1:2, :]
print(row2, row2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [16]:
col1 = a[:,1]
print(col1, col1.shape)
col2 = a[:, 1:2]
print(col2, col2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


### Interger array indexing

In [17]:
# When you index into numpy arrays using slicing, 
# the resulting array view will always be a subarray of the original array. 
# In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array.

In [18]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
print(a[[0,1,2],[0,1,0]])
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]
[1 4 5]


In [20]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [21]:
b = np.array([0,2,0,1])
print(a[np.arange(4),b])

[ 1  6  7 11]


In [22]:
print(a.dtype)

int32


In [23]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [24]:
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [25]:
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [26]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [27]:
print(x)
print(np.sqrt(x))

[[1. 2.]
 [3. 4.]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [28]:
v = np.array([9,10])
w = np.array([11, 12])
#9     11
#10    12

In [29]:
# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


#### axis=0, axis =1

In [30]:
x = np.array([[1,2],[3,4]])
print(x)
print(np.sum(x))  # Compute sum of all elements 1 + 2 + 3 + 4
print(np.sum(x, axis=0))  # Compute sum of each column 
print(np.sum(x, axis=1))  # Compute sum of each row

[[1 2]
 [3 4]]
10
[4 6]
[3 7]


In [31]:
print("x")
print(x)
print("\nx Transpose")
print(x.T)

x
[[1 2]
 [3 4]]

x Transpose
[[1 3]
 [2 4]]


## Broadcasting

#### Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

In [32]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


##### This works; however when the matrix x is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix x is equivalent to forming a matrix vv by stacking multiple copies of v vertically, then performing elementwise summation of x and vv. We could implement this approach like this:

##### Use tile()

In [33]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [38]:
v = np.array([1,2,3])
w = np.array([4,5])
print(v.shape)
print(w.shape)

(3,)
(2,)


In [37]:
a = np.reshape(v, (3,1))
a.shape

(3, 1)

In [39]:
print(np.reshape(v, (3,1)) * w) # 3x1 * 1x2 => 3x2 matrix


[[ 4  5]
 [ 8 10]
 [12 15]]


In [42]:
x = np.array([[1,2,3], [4,5,6]]) # x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
print(x+v)

[[2 4 6]
 [5 7 9]]


In [53]:
print("x.T\n", x.T, x.T.shape)
print("w\n",w, w.shape)
print("\nAfter compute\n")
print((x.T + w).T)


x.T
 [[1 4]
 [2 5]
 [3 6]] (3, 2)
w
 [4 5] (2,)

After compute

[[ 5  6  7]
 [ 9 10 11]]
